[env]
_.file = '.env'

[tools]
node = "24"
pnpm = "10"

[tasks."pre-commit"]
description = "Execute before commit"
run = """
pnpm check
"""

[hooks]
postinstall = """
pnpm install
mise generate git-pre-commit --write --task=pre-commit
"""
